import ThemeChanger from "@/components/ThemeChanger";
import Head from "next/head";
import { BsMoonStars, BsSun } from "react-icons/bs";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header className="flex justify-between items-center p-4">
          <h1 className="text-3xl">Milos Djurica</h1>
          <nav>
            <ul className="hidden md:flex space-x-2 themeChanger px-4 py-2">
              <li>Home</li>
              <li>/</li>
              <li>About</li>
              <li>/</li>
              <li>Projects</li>
              <li>/</li>
              <li>Skills</li>
              <li>/</li>
              <li>Resume</li>
              <li>/</li>
              <li>Contact</li>
            </ul>
          </nav>

          <ThemeChanger />
        </header>
      </main>
    </>
  );
}
